# Generated by Django 3.1.4 on 2021-01-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=15)),
                ('eventDesc', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='college',
            field=models.CharField(default='college', max_length=30),
        ),
        migrations.AddField(
            model_name='register',
            name='dept',
            field=models.CharField(default='dept', max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='eventName',
            field=models.CharField(default='event', max_length=50),
        ),
    ]
